### PR TITLE
Sim1robust

### PR DESCRIPTION
**Pull request by tholden**
Cherry picked the relevant changes from the old pull request https://github.com/DynareTeam/dynare/pull/689
I misunderstood how pull requests worked initially.

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
So if I understand the three commits correctly, in the end you just replace the left divide
```
dy = -A\res;
```
by 
```
    if norm( b ) < sqrt( eps ) % then x = 0 is a solution
        x = 0;
        return
    end
   
    WarningState = warning( 'off', 'all' );
    
    try % wrap in a try-catch block to ensure that the WarningState is always reset
        x = A\b;
        x( ~isfinite( x ) ) = 0;
        relres = norm( b - A * x ) / norm( b );
        if relres > 1e-6
            fprintf( 'WARNING : Failed to find a solution to the linear system.\n' );
        end      
    catch Error
        warning( WarningState );
        error( Error ); %rethrow
    end
    warning( WarningState );
end
```
I think that this makes a lot of sense. I was just wondering which type of errors do you have in mind that you are trying to control with the try-catch statement? My feeling is that any problems that might trigger a crash should be controlled earlier on and not within this function.

**Comment by JohannesPfeifer** [comment]
@tholden A last thing. Your pull request still contains the ```lin_solve_robust.m```, but it is nowhere used now.

**Comment by tholden** [comment]
The try catch is a standard "pattern" when temporarily modifying a global state. Without it, an error thrown in the inner block would leave all warnings disabled. To be honest, given that I find it helpful to disable warnings quite often, this is a block of code that I've written so many times I do it on auto-pilot, without thinking too much about what errors might be thrown in the middle (from looking at it, you could potentially get errors if b was a matrix). But since it's essentially zero cost (it is not like you can disable exception handling in MATLAB as you can in C++) it seems like good programming practice.

The lin_solve_robust.m file is still in there as an alternative which may be useful in some circumstances. Perhaps an option should be included to use it, or just trust sophisticated users to change lin_solve to lin_solve_robust if necessary. Or just delete it. It's up to you.

**Comment by houtanb** [comment]
superseded by #1052

**Pull request closed without merging**
