### PR TITLE
Fix bug in use_shock_groups

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Option was not written to correct subfield of options_-structure. Related to 7cd56e96877de4ed2dd22bb579884ab292034d71

### CODE REVIEW

**Comment by houtanb** [comment]
@JohannesPfeifer are you sure about this change? `plot_shock_decomposition` uses `o_psd_use_shock_groups` which prints the option to `plot_shock_decomp.use_shock_groups`.

`o_use_shock_groups` is used by `shock_decomposition` and `realtime_shock_decomposition` not by `plot_shock_decomposition`

**Comment by JohannesPfeifer** [comment]
@houtanb I would like @rattoma to confirm the correctness, but I am pretty sure. `shock_decomposition` internally relies on `plot_shock_decomposition`. Having the option in a different field means that the latter cannot use it.

**Comment by rattoma** [comment]
@JohannesPfeifer @houtanb 
Indeed plot_shock_decomposition is always used within `shock_decomposition` and `realtime_shock_decomposition` as factorized plotting utility. 

I do not recall why we needed the extra field `options_.plot_shock_decomp` on top of `options_.shock_decomp`, but the patch proposed by @JohannesPfeifer is correct, since plot_decomposition would look at its own list of options ... thank you

**Comment by houtanb** [comment]
@rattoma @JohannesPfeifer if this is the case, then there are two things:
1) We should delete the option `o_psd_use_shock_groups` and replace it by `o_use_shock_groups`
1) I don't understand then the change in `matlab/global_initialization.m`. If this field is not used why not remove it completely?

**Comment by rattoma** [comment]
I may start recalling: the reason should be to avoid the plot options to be persistent, which suggests that the pre-processor should always re-set to default all plot options before any new call to `plot_shock_decomposition`.
If this is the case, then we have to keep the current layout.

**Comment by houtanb** [comment]
This is what this sort of change is for. So that the option passed to the various commands are not persistent.....

**Comment by rattoma** [comment]
yes, which means this PR is fine. many thanks

**Comment by houtanb** [comment]
Ah, so I had misunderstood. Now you are fine with the persistence of options and will not change the backend? If this is the case, then @JohannesPfeifer should make the changes outlined here: https://github.com/DynareTeam/dynare/pull/1470#issuecomment-309430672

**Comment by JohannesPfeifer** [comment]
@houtanb Now I am confused what needs to be done

**Comment by houtanb** [comment]
@JohannesPfeifer the changes that are in this comment. @rattoma is ok with the idea of merging these two options. But, the change you implement in f595d37 has two options, `o_psd_use_shock_groups` and `o_use_shock_groups` that do the same thing.

Also, I don't understand the change you made to `global_initialization.m`. Why do we need `options_.shock_decomp.use_shock_groups` if we always reference `options_.plot_shock_decmp.use_shock_groups`?

**Comment by rattoma** [comment]
@houtanb no sorry, I'm OK with NOT having persistent options for plot_shock_decomposition

**Comment by houtanb** [comment]
@JohannesPfeifer are the changes to be made here clear or would you like me to make the changes?

**Comment by JohannesPfeifer** [comment]
@houtanb I gave it another try

**Comment by houtanb** [comment]
@JohannesPfeifer your change looks good. Can we also remove line 33 of `plot_shock_decomposition.m`? It seems useless.....

**Comment by JohannesPfeifer** [comment]
@houtanb Done

**Pull request merged**
