### PR TITLE
Condition test whether varobs was defined on existence of field

### PR DESCRIPTION
**Pull request by JohannesPfeifer**

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@houtanb I am not sure about this. Maybe we should think this through first. At some point, we agreed that every field of ```options``` that can exist, should also exist. This would argue for setting ```options_.varobs``` to empty in ```global_initialization``` and just drop this check for existence.

**Comment by houtanb** [comment]
@JohannesPfeifer then we should make a final decision on that and implement that throughout the code for all ```options_``` fields. But, as it stands now, this commit can be simplified.

**Comment by JohannesPfeifer** [comment]
@houtanb Could you then please open a ticket for this issue. I have amended the commit accordingly.

**Comment by JohannesPfeifer** [comment]
@houtanb Done

**Pull request merged**
