### PR TITLE
utility to decompose initial condition effect

### PR DESCRIPTION
**Pull request by rattoma**
added new utility

### CODE REVIEW

**Comment by houtanb** [comment]
@rattoma please `rebase` this on `origin/master`. You will see it doesn't work because the options for `plot_shock_decomposition` are stored in the wrong substructure of `options_`. Also please change the date to 2017 instead of 2009-2016, and fix line 2 to match the function call.

**Comment by rattoma** [comment]
@houtanb thank you. I actually re-based but overlooked the move of options, sorry. should be fixed now.

**Comment by houtanb** [comment]
@rattoma does this need an interface?

**Comment by rattoma** [comment]
@houtanb we may leave this without and undocumented.
Ideally, we could add an interface with only a subset of plot_shock_decomposition options, namely:

- varlist
- type
- detail_plot
- plot_init_date
- plot_end_date
- steadystate
- write_xls

**Comment by houtanb** [comment]
@rattoma what should the defaults be for `plot_init_date` and `plot_end_date`? These have not been set for `plot_shock_decomposition` by the way. Do you want me to add them there too?

**Comment by rattoma** [comment]
@houtanb  should be empty. also for plot_shock_decomp thanks!

**Comment by houtanb** [comment]
@rattoma I pushed the changes in 1891ab70f87561ce5597c9c5202606324d331685. Would the correct description in the manual be:
`plot_init_date` = DATE; If passed, this is the beginning date for the plot.

What is the default value for this option? What is the default value for the end date? By this I mean, not `[]` which is what it is set to, but the date you use in the code?

**Comment by houtanb** [comment]
@rattoma do you want to make the entry in the manual? At the same time you can make the entry for `initial_condition_decomposition`. Please let me know

**Pull request merged**
