### PR TITLE
Clarify the timing convention in dynare++

### LINKED ISSUE #1244: Clarify Dynare++ timing convention
See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=8393
Using time to build is confusing and should be clearly documented

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Closes #1244

### CODE REVIEW

**Comment by MichelJuillard** [comment]
This file is authored by Ondra Kamenik and dated 2011. You can't simply modify it.

**Comment by JohannesPfeifer** [comment]
@ Then how do we proceed in such cases? We have a bunch of files authored by particular persons that we distribute in the documentation. How can we ever alter them?

**Comment by MichelJuillard** [comment]
Each case is probably different. In this one, you should contact O. Kamenik and suggest him the modification. We should add to the date "Revised September 2016"

**Comment by JohannesPfeifer** [comment]
@MichelJuillard OK. Could you then please contact Ondra?

**Comment by JohannesPfeifer** [comment]
Ondra has replied that he is OK with the commit. It can now be merged.

**Pull request merged**
