### PR TITLE
Remove error-display from dynare_solve.m

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Prevents estimation crashing when invalid starting values for steady state computation arise during e.g. mode-finding

### CODE REVIEW

**Comment by MichelJuillard** [comment]
When the problem occurs, you return info=1, this is not the proper code in print_info

**Comment by JohannesPfeifer** [comment]
@MichelJuillard As far as I can see, the error handling is not done in `dynare_solve`, but later functions like `evaluate_steady_state`. `dynare_solve` always only returns 0 or 1.

**Comment by MichelJuillard** [comment]
Yes, of course, dynare_solve is now a generic function for general nonlinear system of equation, not only for computing the steady state. But then, in the debug message, we should remove references to steady or static

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Then we should probably get rid of the debug message, because there is no way to ascertain on which function dynare_solve is called and the call to `display_problematic_vars_Jacobian` will return wrong results.

**Comment by MichelJuillard** [comment]
OK, let's get rid of it.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I amended the commit to only provide the debugging output for steady state computation. That should solve the issue.

**Comment by MichelJuillard** [comment]
I don't see the change in the commit

**Comment by JohannesPfeifer** [comment]
@MichelJuillard The new part is the test whether the caller is evaluate_steady_state in line 56 of 444cf1735e98183adf91da03c90eb67ac199025f

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I did another round in 	94128bd. I would like to keep the call to `display_problematic_vars_Jacobian` for the steady state case. because I rely heavily on it with mod-files of users in the forum.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Ok. In 5e4f52e542c3a738d8d2e4ea2f70f456edb15556 I removed all application-specific output.

**Comment by MichelJuillard** [comment]
OK for dynare_solve. Please, split the PRs.  In evaluate_steady_state:
1) we don't want to bring back fvec and fjac in normal circumstances, only if there is an error flag. Repeat the call to dynare_solve requesting fvec and fjac inside the debug block
2) You call the debug block even if there is no error in the return of dynare_solve

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I would prefer to always bring back `fvec` and `fjac`. As they are always computed by `dynare_solve` regardless of whether we output them, this should be a costless operation. In contrast, calling `dynare_solve` a second time to recompute the Jacobian is really expensive when someone runs estimation in debug mode.

**Comment by MichelJuillard** [comment]
@JohannesPfeifer we don't care about expensive when debug is on and an error has been caught
Returning a matrix is not costless in Matlab, because space is allocated and the matrix is copied. For large Jacobian, it is a useless operation in normal circumstances

**Comment by JohannesPfeifer** [comment]
@MichelJuillard Ok. Done.

**Pull request merged**
