### PR TITLE
load_mh_file: recompute results by default and load on request

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Prevents general overwriting of results in oo_ and having stale results

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@rattoma Is this what you envisioned? I went for recomputing results by default as this is not computationally intensive and prevents having stale results in `oo_`. The commit also only loads the fields that were otherwise computed instead of overwriting the whole results structure.

**Comment by rattoma** [comment]
@JohannesPfeifer yes. this looks the perfect fix!

**Comment by stepan-a** [comment]
@JohannesPfeifer After a rebase on master `estimation/fs2000_model_comparison.mod` fails. I obtain the following log

```
model_comparison:: The user supplied prior distribution over models is improper...
model_comparison:: The distribution is automatically rescaled!


Model Comparison (based on Modified Harmonic Mean Estimator)
Model                                                fs2000  fs2000_initialize_from_calib
Priors                                             0.400000                      0.600000
Log Marginal Density                            1186.277615                   1182.090789
Bayes Ratio                                        1.000000                      0.022792
Posterior Model Probability                        0.977716                      0.022284

********************************************
*** DYNARE-TEST-MATLAB ERROR ENCOUNTERED ***
********************************************
  WHILE RUNNING MODFILE: estimation/fs2000_model_comparison

Error using fs2000_model_comparison (line 263)
Laplace and Harmonic Mean do not match

Error in dynare (line 223)
evalin('base',fname) ;

Error in run_test_matlab (line 38)
  dynare([testfile ext], 'console')

*************************************
```

I do not understand how this relates to your last commit....

**Comment by JohannesPfeifer** [comment]
@stepan-a I will look into it tomorrow. There is a change in `fs2000.mod` that alters the marginal data density estimate and triggers the error.

**Comment by JohannesPfeifer** [comment]
@stepan-a I think I identified the source of the failed test and added a commit resolving it.

**Pull request merged**
