### PR TITLE
Provide informative error message if non-stationary model is estimate…

### LINKED ISSUE #1377: Decide on treatment of qz_criterium in estimation with particle filter
Currently, if a unit root is present, estimation with `order=2` will result in an error. Using `diffuse_filter` will disable the check, but obviously makes no sense for particle filtering. See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=13126

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
…d using particle filter

Closes #1377

### CODE REVIEW

**Comment by stepan-a** [comment]
I am not sure I agree with the message. I have the feeling that we just need to change the initialisation of the filter in this case... I need to check.

**Comment by JohannesPfeifer** [comment]
@stepan-a At the current stage, the message is correct, because we have not implemented a proper initialization for the non-stationary states. I expect to lift this restriction, but not for `4.5`.

**Comment by stepan-a** [comment]
@JohannesPfeifer The initialization with a diagonal matrix is implemented. I need to check that it works.

**Comment by JohannesPfeifer** [comment]
@stepan-a It seems to work, but we do not have an interface in place to select `options_.particle.initialization` (and documentation is missing). 
We also need a way to set `qz_criterium` for the particle filter. Currently. the only way to do this is the `diffuse_filter`-option.

**Comment by stepan-a** [comment]
Fixed. Added option `nonlinear_filter_initialization` in f9a462bf07225f3ca018c6f3bdb97cb0f65d48db. If the model has unit roots, the user must set `nonlinear_filter_initialization=3`.

**Pull request closed without merging**
