### PR TITLE
Shock decomp

### PR DESCRIPTION
**Pull request by rattoma**
This pull request contains a number of bug fixes to the new plottting and realtime  shock decompositions.
All bug fix commits should also be cherry picked to 4.5
there is also a new option `fast_realtime` that should apply to
`options_.shock_decomp.fast_realtime`
for the 
`realtime_shock_decomposition`
command.

### CODE REVIEW

**Comment by stepan-a** [comment]
Manually merged in master. Still needs to be added in 4.5 branch.

**Comment by JohannesPfeifer** [comment]
@stepan-a Needs to be combined with #1563

**Comment by stepan-a** [comment]
@JohannesPfeifer I saw, but I need to test first...

**Comment by stepan-a** [comment]
Cherry picked in 4.5 branch.

**Pull request closed without merging**
