### PR TITLE
Clarify unit test dependencies

### LINKED ISSUE #1018: fix test suite bugs
In email of 6/8/2015 on the dev list, @JohannesPfeifer reported dependencies of the test suite that don't make sense. fix these

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
fs2000 is needed by other tests while fs2000_mf.mod is redundant and not called. Thus, its dependency definition can be deleted

Closes #1018

### CODE REVIEW

**Comment by houtanb** [comment]
Why is ```fs2000_mf.mod``` redundant?

**Comment by JohannesPfeifer** [comment]
It tests using a mode-file. As we have dozens of other tests loading a mode-file, it was removed from the testsuite some time ago. But we never deleted the actual file.

**Comment by houtanb** [comment]
And what about ```optimizers/fs2000_102.mod``` ?

**Comment by JohannesPfeifer** [comment]
It uses the mode-file created by the ```fs2000.mod```. Thus, the dependency is correctly specified.

**Comment by houtanb** [comment]
Ah sorry, thought it was in ```optimizers/fs2000.mod``` didn't see that it was in fact ```estimation/fs2000.mod```

**Pull request merged**
