### PR TITLE
Test the rank of Pinf in univariate smoother for the subset of observables

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Traps cases where this is not already trapped in compute_Pinf_Pstar.m
Supersedes and thus closes #1427

### CODE REVIEW

**Comment by houtanb** [comment]
@rattoma does this sound good?

**Comment by rattoma** [comment]
@houtanb @JohannesPfeifer  excellent! thank you

**Comment by houtanb** [comment]
@JohannesPfeifer the following tests fail with this modification:
`tests/kalman/likelihood_from_dynare/fs2000_uncorr_ME_missing.mod`
`tests/kalman/likelihood_from_dynare/fs2000_corr_ME.mod`
`tests/kalman/likelihood_from_dynare/fs2000_corr_ME_missing.mod`
`tests/kalman/likelihood_from_dynare/fs2000_uncorr_ME.mod`

**Comment by JohannesPfeifer** [comment]
@houtanb Could you please run the testsuite with the amended commit?

**Pull request merged**
