### PR TITLE
Various improvements to LaTeX output

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
- Adds TeX output for convergence diagnostics and trace plots. 
- Uses booktabs package for neater tables
- Adds ```morefloats``` package to prevent crashes in documents with many floats

### CODE REVIEW

**Comment by MichelJuillard** [comment]
Thanks @JohannesPfeifer . What are the existing test cases that we can used to test these changes?

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I modified the TeX unit test to check for the new feature. The other cosmetic improvement were already covered by this file.

**Comment by JohannesPfeifer** [comment]
@rattoma Could you please have a look at the last commits. They close #981

**Comment by stepan-a** [comment]
@JohannesPfeifer  ```TeX/fs2000_corr_ME.mod``` is failing when I run the testsuite on this branch, but the error does not seem to be related to your commits (the log is available [here](https://gitlab.com/snippets/11569)). I merge and we will see...

**Pull request merged**
