### PR TITLE
Correct initval, endval, and histval documentation

### PR DESCRIPTION
**Pull request by JohannesPfeifer**

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@stepan-a Any progress on this? I am going to teach Dynare this week and hoped the manual of the unstable version would be updated by then. Is there anything controversial about the changes? They simply document the current behavior and the manual still compiled on Sedna.

**Comment by stepan-a** [comment]
@JohannesPfeifer I vaguely remember that I had some semantic problems... But I won't have time to fix this now.

**Comment by JohannesPfeifer** [comment]
@stepan-a If your concerns are not related to substantial content, can't we then just update the manual now and do the semantic fixes later on? For months I have been redirecting people on the forum to this commit to explain the behavior of the different blocks.

**Comment by stepan-a** [comment]
Manually merged.

**Pull request closed without merging**
