### PR TITLE
bug fixes around slice sampler and parallel execution

### PR DESCRIPTION
**Pull request by rattoma**
This should be merged onto the master, not to the oldish slice branch of dynare

### CODE REVIEW

**Comment by MichelJuillard** [comment]
@rattoma your pull request has conflicts. It may be very difficult to resolve them. Could you please break this PR in several smaller parts?

**Comment by rattoma** [comment]
@michel I think the problem is that github wants to merge my PR onto the old `dynare\slice` branch [by chance my local branch has the same name of the dynare/slice branch]. 
How can I proceed? I have to merge it first to my local master and make a new PR?

**Comment by rattoma** [comment]
@MichelJuillard I think I just fixed the issue by manually changing the the PR to merge with the base branch.

**Comment by MichelJuillard** [comment]
@rattoma thanks. That solved the issue

**Pull request merged**
