### PR TITLE
Harmonize FilteredVariables with Updated and Smoothed ones, by adding…

### PR DESCRIPTION
**Pull request by rattoma**
… steady state to stored values, both point estimate and MCMC

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@rattoma I don't think your are handling the `prefilter` part correctly in `prior_posterior_statistics_core`. We should probably wait for the merging of #1214, which stores the constant term explicitly after MCMC and makes adding it to filtered variables straightforward.

**Comment by rattoma** [comment]
OK thanks. Let's take note that `filt_mc_` will have to be adapted accordingly as well. I will re-set my master branch for the moment.

**Comment by rattoma** [comment]
@JohannesPfeifer I updated my PR.

**Comment by stepan-a** [comment]
Manually merged.

**Pull request closed without merging**
