### PR TITLE
Add Windows subsystem for Linux to README

### PR DESCRIPTION
**Pull request by JohannesPfeifer**

### CODE REVIEW

**Comment by stepan-a** [comment]
@JohannesPfeifer Why not, but what is the use of having Dynare compiled on WSL? I also tried on my new laptop, it's far easier to do that rather than building with cygwin, but my understanding is that the produced Mex and preprocessor cannot be used under windows... Did you  run Dynare in WSL with Octave?  Is it possible to install matlab and build against matlab?

**Comment by JohannesPfeifer** [comment]
@stepan-a Yes, I already tried it with Octave and it works. My next step is to install Matlab tomorrow and see whether that works as well. The goal is to provide Windows users with easy access to the Linux version, which in the current form is still more stable and reliable.
In the long-run my goal is to be able to cross-compile on WSL to generate the Windows binaries.

**Comment by stepan-a** [comment]
Okay, I merge. This idea of compiling for windows in WSL crossed my mind too... But finally I prefer to work with docker (which seems easier to maintain).

**Comment by taizihuang** [comment]
@JohannesPfeifer Hi, I wonder if you already succeed in installing MATLAB on WSL. My attempt has failed.

**Comment by JohannesPfeifer** [comment]
@taizihuang My previous attempts resulted in Java errors during the installer. So I am still trying. What was your experience? Please post your error message here so I can investigate this further

**Comment by taizihuang** [comment]
@JohannesPfeifer 

htz@PC:~$ ./install
Preparing installation files ...
Installing ...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f79964811a0, pid=47, tid=140160745604864
#
# JRE version: 7.0_11-b21
# Java VM: Java HotSpot(TM) 64-Bit Server VM (23.6-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libinstutil.so+0xa11a0]  Ox0c6ee92b372820cc+0x50
#
# Core dump written. Default location: /home/htz/core or core.47
#
# An error report file with more information is saved as:
# /home/htz/hs_err_pid47.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
Aborted (core dumped)
Finished
htz@PC:~$ sudo ./install -javadir /opt/jdk/jdk1.8.0_05/jre
Preparing installation files ...
Installing ...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbf9fb811a0, pid=100, tid=140461700417280
#
# JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.5-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libinstutil.so+0xa11a0]  Ox0c6ee92b372820cc+0x50
#
# Core dump written. Default location: /home/htz/core or core.100
#
# An error report file with more information is saved as:
# /home/htz/hs_err_pid100.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
Aborted (core dumped)
Finished
===========================================================

**Comment by JohannesPfeifer** [comment]
@taizihuang Were you trying to do a silent install? You did not pass an installation file to the installer, it seems.

**Comment by taizihuang** [comment]
@JohannesPfeifer I've tried that too, and the result failed me the same.

**Pull request merged**
