### PR TITLE
BVAR: add irfs to manual and unit test

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
@sebastien-villemot Are you OK with the changes to the documentation, which bears your name?

### CODE REVIEW

**Comment by sebastien-villemot** [comment]
Sure.

By the way, you should probably add your name, and fix my email address (the @dynare.org one is no longer valid).

**Comment by JohannesPfeifer** [comment]
@sebastien-villemot I will do so. Which email should I use?  I should also update your affiliation. Currently it is "Paris School of Economics and CEPREMAP"

**Comment by sebastien-villemot** [comment]
It's probably better to leave PSE/CEPREMAP, because this is where I was writing this document.

Concerning the email, it's actually better to remove it: I am not sure I will be able/willing to answer anymore questions about this document.

**Comment by JohannesPfeifer** [comment]
Ok, I updated the PR

**Comment by stepan-a** [comment]
Manually merged.

**Comment by JohannesPfeifer** [comment]
@stepan-a That explains a lot. I was already wondering where the square root matrix identification came from...

**Pull request closed without merging**
