### PR TITLE
Integrate robust linear solver for stack_solve_algo=0

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Supersedes #984 

To be done: add interface option for ```robust_lin_solve``` to set ```options_.simul.robust_lin_solve=1```

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
Sidenote: I don't know what changed in the unstable version, but in case of multiple solutions, the unstable version returns a different solution than the stable version. This pull request seems to restore the previous behavior.

**Comment by houtanb** [comment]
@JohannesPfeifer should we close #984?

Once this is merged, please create an issue for the interface change

**Comment by JohannesPfeifer** [comment]
Yes, this closes #984

**Comment by MichelJuillard** [comment]
@JohannesPfeifer, 
1. what is the reference for Tom Holden robust linear solver?
2. Our experience is that bigcstab and gemres rarely work for this type of models
3. We need to think how to organize the multiple options available to solve the perfect foresight model

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I don't know the reference and don't have experiences with the ```robust_lin_solve```. Maybe @tholden can help out

**Comment by tholden** [comment]
Sorry for the delayed reply. I created these files when having some problems with perfect foresight solutions to a model with multiple occasionally binding constraints. lin_solve_robust takes a super paranoid, try everything approach, as a final desperate attempt for very stubborn models, and the pseudo-inverse (the last thing it tries) really ought to always work, though it will be slow (hence trying it last). @jonswarbrick ought to have the latest mod file for the model which was originally giving problems (Jonathan: this is the perfect foresight version of our occasionally binding financial frictions paper).

**Comment by JohannesPfeifer** [comment]
@stepan-a I talked to Tom and would like to add this as an option the user can try if everything else fails. The idea is to sequentially test approaches to "inverting" an ill-conditioned A in the hope that one of them works. If none of them does, use the pseudo-inverse as a last resort. This option of couse won't be quick and clearly is not a default choice, but might be useful in pathological cases. Therefore, I don't see why we should not support it.

**Pull request merged**
