### PR TITLE
Fixes regarding initval file

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Deals with #806 by allowing row and column vectors. Does not alter the field structure yet.

### CODE REVIEW

**Comment by stepan-a** [comment]
@JohannesPfeifer, Okay. I need to do a manual merge (because I moved some of the routines you changed here).

**Comment by JohannesPfeifer** [comment]
@stepan-a Ok. Thanks.

**Comment by stepan-a** [comment]
@JohannesPfeifer I merged your commits with master in branch [merge-initvalfile-fix](https://github.com/DynareTeam/dynare/compare/merge-initvalfile-fix). But I still have a problem with commit bb92f9bc2a86cefdcd9e2295970a6e7ef362d272 where you add binary mat files for the tests. Can you replace these files with a matlab script or a mod file generating these data, with a PR on [merge-initvalfile-fix](https://github.com/DynareTeam/dynare/compare/merge-initvalfile-fix) branch?

**Comment by JohannesPfeifer** [comment]
How do I account for the dependence between files then? The script that generated the binary files is the commented part of ```ramst_initval_file_data.m``` in commit bb92f9bc2a86cefdcd9e2295970a6e7ef362d272

**Comment by stepan-a** [comment]
The dependence is defined in the ```tests/Makefile.am```. I will look into it.

**Pull request merged**
