### PR TITLE
Implement posterior_nograph option

### LINKED ISSUE #1356: introduce posterior_nograph option
I think it would be useful to have an option like:

`options_.posterior_nograph`

with default value at 0 like standard nograph. 

This option would allow performing all possible posterior subdraws for irfs, smoothed variables etc, but avoiding to produce thousands of useless graphs that are currently done [for large models at least]. 

I think it would also be useful to make a distinction w.r.t. `options_.nograph` since the latter would not trigger prior/posterior plots of parameter estimates which would be required in any case. 

And by the way, `pm3` and `posterior_irf` do not seem to honor the nograph option: plots are made in any case. So at least we should make sure `nograph` would work properly?

If you agree, I would make the appropriate changes to the matlab `pm3` and `posterior_irf` routines with `posterior_nograph` [the preprocessor could be updated with this extra option, then].

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Also finishes implementation and documentation of nograph option of shock_decomposition.m
Closes #1356

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@rattoma I added the changes you sent me and the unit tests works.

**Comment by rattoma** [comment]
@JohannesPfeifer many thanks!

**Comment by houtanb** [comment]
@JohannesPfeifer You need to add the options `posterior_nograph` and `posterior_graph` to the `estimation` command in the manual.

Also, I would've split these commits up differently. 1 commit for the change in `nograph` for `shock_decomposition`. And another commit for the `posterior_graph` and `posterior_nograph` options, combining the preprocessor/manual changes with e0b6318f5483ec195ea8b5b57a28507b32b68127

**Comment by JohannesPfeifer** [comment]
@houtanb Thanks. I adjusted the PR accordingly

**Pull request merged**
