### PR TITLE
Document lik_init=5 and add unit test for lik_init

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Related to #992

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@stepan-a The implementation of ```lik_init=5``` is still not complete. See the crashes in the unit tests

**Comment by stepan-a** [comment]
Thanks, I try to fix this before merging (do not want to add a new failing test for a hidden feature).

**Comment by stepan-a** [comment]
I fixed the issue with lik_init equal to 5 (I pushed the fix in a personal branch [here](https://gitlab.ithaca.fr/Dynare/dynare/commits/lik_init_5) where I also rewrote the tests) but I found another issue with ```lik_init==3``` with the estimation in levels of fs2000...

**Comment by JohannesPfeifer** [comment]
Which issue do you encounter?

**Comment by stepan-a** [comment]
```schur_statespace_transformation``` routine returns NaNs for ```Pstar```... But it's most likely an issue with my test.

**Comment by stepan-a** [comment]
@JohannesPfeifer I rebased my branch [here](https://gitlab.com/stepan-a-dynare/dynare/commits/lik_init_5) on master. All remaining issues are fixed. Did you intend to compare likelihood values returned for different initializations? These values, in some cases, are very different, and this is expected. So I do not see the point in such a comparison (I may have misunderstood your idea)... But I suppose that these discrepancies should narrow when the sample size is increased. In the current state, at least, we test that all the options for initialization are working.

**Comment by JohannesPfeifer** [comment]
@stepan-a Could it be that this change needs to be ported to DsgeSmoother.m?

**Pull request merged**
