### PR TITLE
GSA fixes and extensions

### PR DESCRIPTION
**Pull request by rattoma**
I am not sure if test routine ls2003a.mod is included in the testsuite: this is to check irf and moment calibration
still updating documentation...

### CODE REVIEW

**Comment by stepan-a** [comment]
I agree with @marco. The issue with the size of the saved ```*.mat``` files is not so obvious and should be dealt with later. Besides I do not think that this is a problem of practical importance because the value of MaxNumberOfBytes is relatively small. This was an issue when I created this mechanism because we had much less RAM than today.

I check/fix the issue with ```ls2003a.mod``` in the testsuite.

**Comment by stepan-a** [comment]
@rattoma I was not able to cherry-pick 0bd8fef2029f27e47f7668247b3ab146d1e7ed81 in 4.4... If you think that the fix should be applied to 4.4, please do a PR for the stable branch.

**Comment by JohannesPfeifer** [comment]
@rattoma For those issues, that affect 4.4, could you also please add them to http://www.dynare.org/DynareWiki/KnownBugs

**Comment by stepan-a** [comment]
@rattoma I already added two lines on the wiki for the commits I could cherry-pick.

**Comment by rattoma** [comment]
Concerning https://github.com/DynareTeam/dynare/commit/0bd8fef2029f27e47f7668247b3ab146d1e7ed81, this is a new feature of 4.5, so no neet to cherry pick it.

**Comment by stepan-a** [comment]
The test suite failed last night because of ls2003a.mod. It appears that this mod files causes a segmentation fault. I did not figure out why... I remove this mod file from the test suite and open an issue.

**Pull request merged**
