### PR TITLE
remove extra exogenous variables

### PR DESCRIPTION
**Pull request by houtanb**

### CODE REVIEW

**Comment by stepan-a** [comment]
@houtanb are you waiting for @MichelJuillard's approval on this one? Did you run the testsuite on this branch?

**Comment by houtanb** [comment]
Yes, I'm waiting on @MichelJuillard to review it

I probably ran the test suite on it, but I don't remember anymore. I can run it again....

**Comment by MichelJuillard** [comment]
@houtanb does this change implies any backward compatibility problems?

**Comment by MichelJuillard** [comment]
@houtanb is there a case in the test suite testing this change?

**Comment by houtanb** [comment]
@MichelJuillard yes. As stated in #841, `.mod` files that declare exogenous variables, don't use them in the `model` block and reference them in other statements will no longer be processed by the preprocessor. Examples of such `.mod` files are listed in #841 

As for the test, I added two `.mod` files with extra exogenous variables: one that should pass and one that should fail.

**Comment by MichelJuillard** [comment]
This will break existing *.mod files, but maybe it is unavoidable. This should be clearly stated somewhere. Somebody should also add to the manual what is the best practice for temporarily desactivating a shock while debugging a model. Removing all mentions of that shock in the *.mod file is not an option

**Comment by MichelJuillard** [comment]
@houtanb nobody reacted to my last post ....

**Comment by houtanb** [comment]
@MichelJuillard I had responded in issue #841 as this is a PR and we should discuss the Issue in the Issue: https://github.com/DynareTeam/dynare/issues/841#issuecomment-271281385

**Comment by houtanb** [comment]
@MichelJuillard I ran the test suite on this branch and it's ok.

**Comment by MichelJuillard** [comment]
I leave it to @stepan-a to decide if he wants to include this change

**Comment by stepan-a** [comment]
Manually merged.

**Pull request closed without merging**
