### PR TITLE
Unit test checking correctness of decision rules against results from…

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
… Dynare 4.3.2

Detects problems as the unnoticed one introduced by f26551509c4a497ee842b08a12797a7b7601db0b

### CODE REVIEW

**Comment by houtanb** [comment]
Please change the commit message as f265515 did not introduce the bug

**Comment by houtanb** [comment]
You also need to remove the ```.mat``` file from the commit.

**Comment by JohannesPfeifer** [comment]
How should I remove the mat-file? I somehow need to save the previous results.

**Comment by houtanb** [comment]
You can save them as a ```.csv```, load the ```.csv```, and then do the comparison

**Comment by JohannesPfeifer** [comment]
Can't we put it on http://www.dynare.org/Datasets as the other binary files?

**Comment by houtanb** [comment]
Ok, yes. But you need to remove the ```.mat``` files from the commit

**Comment by JohannesPfeifer** [comment]
So I should also remove the one that is already in the commit history? Currently, I only do not introduce a new one.

**Comment by houtanb** [comment]
Yes. Ammend the current commit removing the .mat file. Once it's in the history it ways down the git repository

**Comment by JohannesPfeifer** [comment]
I removed them. How do I upload to the server?

**Comment by houtanb** [comment]
I can do that. But I need to figure out how @stepan-a set this up, so may not merge it today.... Please email me the file

**Comment by stepan-a** [comment]
@houtanb you just need to scp the file to ```kirikou.cepremap.org:/srv/d_kirikou/www.dynare.org/Datasets```. I have just added @JohannesPfeifer (jpfeifer) as a member of the ```dynare-web```group so he should be able to do that in the future.

**Pull request merged**
