### PR TITLE
Correct manual on Ramsey

### LINKED ISSUE #944: Fix description of Ramsey timeless perspective in manual
Michel writes: 

```
I don't agree with the part on timeless perspective. Setting the initial
multiplier to its steady state value is not timeless
perspective. "Setting the initial Lagrange multipliers as if optimal
policy was started a long time ago" would take into consideration the
value of the initial state variables.
```

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Closes #944

### CODE REVIEW

**Comment by stepan-a** [comment]
@MichelJuillard Can you check if we can merge this ?

**Comment by MichelJuillard** [comment]
I have a problem with the expression "the Ramsey policy is computed with the Lagrange multiplier being at the steady state" This is unclear because a policy is a rule--a function of state variables--not a trajectory.
I will think about a better formulation.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I meant ```is computed by approximating the equilibrium system around the perturbation point where the Lagrange multipliers are at their steady state```.

**Comment by JohannesPfeifer** [comment]
@MichelJuillard I did another iteration along my suggestion above.

**Pull request merged**
