### PR TITLE
Fix bugs in gsa with morris and posterior sampling

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
- Uses defined number of observations instead of empty options_.nobs (may already solve the problem discussed in #780)
- Only saves variables that actually exist
- Adds unit test

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@rattoma Do you agree with the proposed changes?

**Comment by houtanb** [comment]
@rattoma have you been able to test these changes?

**Comment by rattoma** [comment]
Apologize. Did not have a look yet. Need to catch up since June, also because I have a lot of pushes to re-align to the rest of dynare...
thanks for reminding this.

**Comment by rattoma** [comment]
@JohannesPfeifer @houtanb. Yes, I'm OK with this!

**Comment by houtanb** [comment]
@rattoma thanks

**Pull request merged**
