### PR TITLE
Bug correction in splitting the jacobian into blocks: the vector variabl...

### PR DESCRIPTION
**Pull request by FerhatMihoubi**
...e_2_block is valid only for endogenous variables.

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@FerhatMihoubi Does this also affect Dynare 4.4? If yes, we should cherry pick the fix and add the problem to the bug list.

**Comment by houtanb** [comment]
Thanks @JohannesPfeifer . I cherry-picked the change to 4.4. It's in 2a0aeb6a6f3b3adf2a0a5daf7dced335084c690e

**Comment by JohannesPfeifer** [comment]
@houtanb Thanks. But what is the underlying bug for the bug report page? Does this solve the issue reported in my email to @FerhatMihoubi on December 8th?

**Comment by houtanb** [comment]
@JohannesPfeifer I don't remember your email, but it's due to a problem where an array entry was accessed that was sometimes not set, causing the preprocessor to crash.

**Comment by JohannesPfeifer** [comment]
@houtanb Then it's something different. I opened a ticket for the other issue. As you seem to understand the problem, could you add this to the bug list?

**Pull request merged**
