### PR TITLE
Identification and LaTeX fixes and improvements

### LINKED ISSUE #766: Deal with correlations in identification
Currently, ```identification``` does not support specified correlations and simply crashes. We should either support this or block it. See http://www.dynare.org/phpBB3/viewtopic.php?f=1&t=6156

### LINKED ISSUE #1219: Tabular output of variance decomposition after Bayesian MH estimation
Dear all,

Johannes asked me to open this as an issue. Would it be possible to provide the output from the conditional variance decomposition after Bayesian estimation in tabular form?

Thanks,
Benjamin

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
- Fixes problems with unit tests
- Final changes to make identification run with correlations (closes #766)
- Prevents LaTeX output from being overwritten
- Reduces runtime of most time-consuming unit test
- Adds LaTeX output for Smirnov tests and `model_comparison`
- Uses `dyntable` for Smirnov output
- Resets colormap to previously used `jet`
- Expands `collect_LaTeX_files` to `gsa` subfolders
- Fixes issues with eps-loaders relying on wrong file separator, breaking LaTeX compilation in some cases
- Eliminates `legend` warning message appearing in gsa in recent Matlab versions
- Allows passing optional headerstring to `dyntable`
- Outputs posterior variance decomposition (closes #1219)

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
@rattoma I am now done working on this branch. Could you please look at it and signal changes I should make or that you are ok with everything?

**Comment by rattoma** [comment]
@JohannesPfeifer I looked at the commits and they look okay. I still have to learn `collect_LaTeX_files`, but as far as I can see I am ok with everything. thanks a lot.

**Comment by stepan-a** [comment]
Running the testsuite on this branch, I found an error on TeX/fs2000_corr_ME. The end of the log file is:
```
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mean_3.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mean_4.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mean_5.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mode_1.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mode_2.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mode_3.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mode_4.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_Posterior_Mode_5.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_PriorsAndPosteriors.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_SmoothedMeasurementErrors.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_SmoothedShocks.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_SmoothedVariables.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_UpdatedVariables.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_covar_ex_shocks.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_dsge_post_mean_var_decomp_cond_h1.
tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_dsge_post_mean_var_decomp_cond_h2.
tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_dsge_post_mean_var_decomp_cond_h4.
tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_dsge_post_mean_var_decomp_uncond.t
ex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_geweke.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_sim_autocorr_matrix.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_sim_corr_matrix.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_sim_moments.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_sim_var_decomp.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_th_autocorr_matrix.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_th_corr_matrix.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_th_moments.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_th_var_decomp_cond_h1.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_th_var_decomp_cond_h3.tex.
No file fs2000_corr_ME/Output/fs2000_corr_ME_th_var_decomp_uncond.tex.
No file fs2000_corr_ME/graphs/fs2000_corr_ME_TracePlot_Posterior.tex.
No file fs2000_corr_ME/graphs/fs2000_corr_ME_forcst.tex.
! Output loop---100 consecutive dead cycles.
\clearpage ...rite \m@ne {}\vbox {}\penalty -\@Mi 
                                                  
l.60 ...2000_corr_ME/graphs/fs2000_corr_ME_forcst}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on fs2000_corr_ME_TeX_binder.log.

********************************************
*** DYNARE-TEST-MATLAB ERROR ENCOUNTERED ***
********************************************
  WHILE RUNNING MODFILE: TeX/fs2000_corr_ME

Error using fs2000_corr_ME (line 277)
TeX-File did not compile.

Error in dynare (line 223)
evalin('base',fname) ;

Error in run_test_matlab (line 38)
  dynare([testfile ext], 'console')

*************************************
```

**Comment by JohannesPfeifer** [comment]
@stepan-a That was the problem we talked about. I cannot replicate the problem on my machine. Our guess was it has to do with the TeX-distribution on the server.

**Comment by stepan-a** [comment]
Okay. I have just checked, stable debian has Texlive 2014 while unstable has Texlive 2016. I suppose this is the problem. I upgrade texlive...

**Comment by stepan-a** [comment]
@houtanb thinks that the problem is not related to the version of texlive but to the estension given to the files. Windows and OS X (depending on the configuration of the file system) are case insensitive, while Linux is case sensitive. Under linux ```*.TeX``` and ```*.tex``` are different files. Solution is to be consistent in the naming of the files (eg name all the files *.tex). @houtanb is fixing this issue.

**Comment by JohannesPfeifer** [comment]
@houtanb I can also do this if you want and add it to the PR.

**Comment by houtanb** [comment]
@JohannesPfeifer the issue is not quite as @stepan-a described. Best I could tell, we were being consistent with the naming. _i.e._ everything that was included as a `.TeX` file was also being created as a `.TeX` file. The problem was that `pdflatex` on linux only seems to like files that end in `.tex`. I have already made the fix and am testing it now. Once I push it, having confirmed it works, then I or you can make the changes in the PR.

**Comment by houtanb** [comment]
Just to note: the exact problem is that, regardless of what extension the file has that is included, `pdflatex` adds `.tex`. So, `\include{ls2003/gsa/ls2003_rmse_prior_y_obs_map.tex}` tries to include the file `ls2003/gsa/ls2003_rmse_prior_y_obs_map.tex.tex`. This means that the only solution is to ensure that all Latex files created by dynare end in `.tex`

**Comment by JohannesPfeifer** [comment]
I rebased the branch and ran the testsuite on `TeX/fs2000_corr_ME.mod` on Sedna and it finally works.

**Comment by houtanb** [comment]
@JohannesPfeifer did you run the whole test suite or just on this file?

**Comment by JohannesPfeifer** [comment]
Stéphane and I ran the testsuite on everything before the rebase. After the rebase, I just ran it on the one problematic test.

**Pull request merged**
