### PR TITLE
Remove fsolve dependency from JFVV model

### PR DESCRIPTION
**Pull request by nerdcha**
Thanks @JohannesPfeifer for including this mod file in the examples; a big time-saver! These changes allow the model to be solved without the Optimization Toolbox, which might make it a bit more accessible.

### CODE REVIEW

**Comment by stepan-a** [comment]
@nerdcha The point of this example is to show how to use a ```steadystate``` file with a Newton inside for solving a concentrated version of the static model. I am not sure that your PR helps a lot (Also I do not know the details of this model but the basic(s) NK model I have in mind do have a closed form solution for the steady state).

That said, it is quite true that the dependency of this example on the Matlab's Optimization Toolbox is annoying. Everybody should be allowed to run this example. Dynare provides other solvers (Newton with line search and trust regions  algorithms, ```csolve``` routine developed by Chris Sims, ...). So if the issue is about removing the dependency w.r.t. Matlab's Optimization Toolbox, I would replace ```fsolve```by another routine in the ```steadystate``` file. The available routines can be seen in the ```dynare_solve``` routine (where you can figure out how to use them). It would be even nicer to call ```dynare_solve```.

**Comment by nerdcha** [comment]
Oh right, I see. I like this model because it's basically Smets-Wouters, but they've done the hard work of figuring out the nonlinear equations for Calvo pricing etc. It has a single equation at the core of the steady state which needs a numerical root finder.

I'll take another swing at removing `fsolve`, using `dynare_solve` instead.

**Comment by MichelJuillard** [comment]
@nerdcha, if it is a single equation that needs to be solve, use fzero(). It is in Matlab base, not in a toolbox and more efficient than dynare_solve when there is only one equation.

**Comment by JohannesPfeifer** [comment]
@nerdcha I did the replacement in #1096

**Comment by nerdcha** [comment]
Thanks, that's great!
>
>

**Pull request closed without merging**
