### PR TITLE
Trend prefiltering fixes

### LINKED ISSUE #255: Check for consistent use of dataset_.descriptive.mean vs. bayestopt_.mean_varobs in smoother and estimation
Currently, both structures are still present. prior_posterior_statistics.m sets 

bayestopt_.mean_varobs = dataset.descriptive.mean';

to have both. Thus, use should be made consistent and storage be confined to one structure. As the mean of the data belongs to the dataset and not the estimation, the dataset_ structure is better suited than bayestopt_.

### LINKED ISSUE #679: Fix various bugs related to detrending and prefiltering
- ```dyn_forecast``` adds unlogged steady state if ```loglinear``` is used
- ```dynare_estimation_init``` sets the ```noconstant``` based on the unlogged steady state if ```loglinear``` is used
- when trends are specified as a function of deep parameters, the values are not correctly updated during estimation due to using the base-workspace parameter values and not the updated local ones
- when using trends with the ```prefilter``` option, the mean shift due to the trend is not accounted for
- when using ```first_obs>1```, the higher trend starting point is not taken into account (leads also to problems in recursive forecasting)

### PR DESCRIPTION
**Pull request by JohannesPfeifer**
Mostly fixes #679 and closes #255, #803, and #804.
Still to be done: 
- document new options once implementation is OKed
- check treatment of various options and trends in smoother used in ```imcforecast.m``` 
- Check treatment of these issues in ```identification```
- Adjust ```convert_dyn_45_to_44``` to reflect these changes

### CODE REVIEW

**Comment by JohannesPfeifer** [comment]
Also fixes #780

**Comment by stepan-a** [comment]
@JohannesPfeifer Thanks for splitting your changes into multiple commits. I still have a doubt about c32b1ec43a7047fe3bebf85913c56c649a972991 (#780). Whenever possible we should avoid to version binary files (because it makes no sense to track history of a binary file and because we need to know where the data are coming from to understand the test). In 2d3a80c7fdaa32c6cf57ed09ca285f4bb511e697 could you replace the ```*.mat``` files by matlab scripts (or mod files) generating these files?

**Comment by JohannesPfeifer** [comment]
@stepan-a I was also reluctant to add the binary mode-files. But it turned out that doing mode-finding with ```mode_compute=9``` or ```mode_compute=10``` took a long time given the size of the data. That is why I opted to include the saved mode-files. Given that there are 16 mod-files that require mode-finding, this would add about 8 hours to the run-time of the test-suite. Thus, I thought it would be preferable to provide the mode (they were generated by the same mod-files).

**Comment by stepan-a** [comment]
@JohannesPfeifer Why would we need to use ```mode_compute=9, 10``` for testing that there is no problem with profiteering of the data?

**Comment by JohannesPfeifer** [comment]
I basically test whether the estimation runs away from the correct previous values. But you are correct that it makes more sense to start at the calibrated true value and run mode_compute=4. I changed it that way

**Comment by JohannesPfeifer** [comment]
@MichelJuillard @stepan-a From my perspective, this is the last big bugfix remaining for 4.5, but I guess there are still many kinks to be smoothed out. I now rebased it to reflect all the pull requests committed today. Any feedback is highly appreciated

**Comment by stepan-a** [comment]
Done in #1145

**Pull request closed without merging**
